### PR TITLE
Update Wormhole Path Colors for Reduced and VOC

### PR DESCRIPTION
**Pull request by LordMrcS**
Replaced the reduced and verge of collapse path colors to make it clearer.
Here is a before and after:

Before
before

After
after

### CODE REVIEW

**Comment by DmitryPopov** [comment]
@DanSylvest any comments/issues?

**Comment by DanSylvest** [comment]
Looks good. Let's try it :)

**Comment by LordMrcS** [comment]
Updated PR merging main. Can try again now.

**Comment by DmitryPopov** [comment]
It'll be available on our [test server](https://wanderer-test.fly.dev/welcome?invite=d05e8848-f813-4db6-91fe-510eac436d37) soon:

**Pull request merged**
